# Generated by Django 2.2.15 on 2020-09-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200908_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
