# Generated by Django 2.2.15 on 2020-09-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
