# Generated by Django 2.2.15 on 2020-09-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
