# Generated by Django 2.2.15 on 2020-09-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200920_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
