# Generated by Django 2.2.15 on 2020-09-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_delete_image'),
    ]

    operations = [
    ]
