# Generated by Django 2.2.15 on 2020-09-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
