# Generated by Django 2.2.15 on 2020-09-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_article_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
