# Generated by Django 2.2.15 on 2020-09-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
