# Generated by Django 2.2.15 on 2020-09-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20200928_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
