# Generated by Django 2.2.15 on 2020-10-07 11:53

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
