# Generated by Django 2.2.15 on 2020-10-07 12:15

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='Active', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
