# Generated by Django 2.2.15 on 2020-10-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
