# Generated by Django 2.2.15 on 2020-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnailimage',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
