# Generated by Django 2.2.15 on 2020-10-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_thumbnailimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnailimage',
            new_name='thumbnail_image',
        ),
    ]
