# Generated by Django 2.2.15 on 2020-10-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201008_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_image',
            new_name='thumbnail_Image',
        ),
    ]
