# Generated by Django 2.2.15 on 2020-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201009_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_Image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
