# Generated by Django 2.2.15 on 2020-10-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_Image',
        ),
    ]
